### ISSUE TITLE
SteamVR crashes when using PVR

### ISSUE THREAD

**Issue by StijnGM** [ShootingKing-AM/PhoneVR#64]
When PVR is disabled SteamVR launches normally, but when I enable PVR and restart SteamVR it turns it back off and gives a notification that SteamVR crashed.

**Comment by ShootingKing-AM** [comment]
Can you provide the following details ?

**Describe the bug/issue**
A clear and concise description of what the bug is.

**Local (your) Time when Issue has occured**
1-Jan-2021, 15:30:00 Hrs

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Envirnoment (please complete the following information):**
 - Desktop OS: [e.g. Windows 10 1680 etc..]
 - Android OS: [e.g. 7.1, 9, 11 etc..]
 - Mobile Device Model [e.g. Xiaomi Mi Note10]

**Additional context**
Add any other context about the problem here.

**Attached Logs**
Attach required logs(yes litreally nothing can be fixed without logs :D) from your Dektop and Mobile end. ([Here](https://github.com/ShootingKing-AM/PhoneVR#issue--bug-reporting) is how to get logs)

**Comment by StijnGM** [comment]
Never mind, it 'fixed itself'.
I don't know what I did, maybe a pc restart, but I tried that multiple times.
